### ISSUE TITLE
Investigate questionable repairkit behaviour

### ISSUE THREAD

**Issue by alexdunnjpl** [NASA-PDS/registry-sweepers#119]
### 💡 Description

See OP here: https://github.com/NASA-PDS/registry-sweepers/issues/108#issue-2145296474

psa-prod repairkit completed 6m42s - questionably-round 80k products affected, then 40k the next execution, then 19786, then 0 - check this later

**Comment by alexdunnjpl** [comment]
Still occurring - appears to be terminating loop approximately halfway through

```
Query 6642d:  57%|███████████▉         | 121500/214809 [02:27<01:53, 825.18it/s]
2024-08-26 20:08:58,326::opensearch::INFO::POST https://b3rqys09xmx9i19yn64i.us-west-2.aoss.amazonaws.com:443/atm-registry/_bulk [status:200 request:0.952s]
2024-08-26 20:08:58,331::pds.registrysweepers.utils.db::INFO::Updated documents for 121500 products!
```

**Comment by alexdunnjpl** [comment]
This seems almost certainly due to the fact that each (update) page writes values to documents in the query set which exclude them from the query set, breaking consistency of the pagination over the query set.  I haven't worked out the details of _why_ this occurs, yet, but I'm not sure that's valuable.

@jordanpadams @tloubrieu-jpl there are a few options here

- rely on registry-sweepers' repeated execution to get all data fixed (each run will fix ~1/2 the data until that quantity falls below the update page size of 20k, at which point it'll fix up the whole remaining portion)
- have repairkit run recursively (ish) until no records require fixing (quick bandaid that eliminates the delay of waiting for repeated sweepers runs, but pretty hacky)
- switch repairkit to make a fresh query for every page of 20k documents, rather than attempting to paginate, terminating when no records are returned (this is the proper fix).

**Comment by jordanpadams** [comment]
@alexdunnjpl per the last option, one thing of note was something @al-niessner mentioned regarding delay time in records actually being updated in AOSS. We may need to watch that this doesn't just run continuously.

**Comment by alexdunnjpl** [comment]
@jordanpadams there is a theoretical potential for redundant work, but no possibility of running continuously, because even if an updated-but-not-refreshed page (or portion thereof) is re-queried and resubmitted for update, it _will_ be updated and excluded from the result-set in short order.

**Comment by jordanpadams** [comment]
@alexdunnjpl copy that
