### ISSUE TITLE
Implement functional tests for provenance.py

### ISSUE THREAD

**Issue by alexdunnjpl** [NASA-PDS/registry-sweepers#13]
## 💡 Description
Reference [`AncestryFunctionalTestCase`](https://github.com/NASA-PDS/registry-sweepers/blob/9e05c2e16eef5d999fb99f063a0bef855edba5d7/tests/pds/registrysweepers/test_ancestry.py) and do something similar.

@jordanpadams is this a reasonable priority once the ancestry metadata PR is closed out?  We know provenance works via manual testing but it'd be nice to be able to back that up and have regression testing for it.

**Comment by tloubrieu-jpl** [comment]
Hi @alexdunnjpl , did you start that ? If not I am thinking we could move that ticket out of the sprint as `not a priority`

**Comment by alexdunnjpl** [comment]
@tloubrieu-jpl nope, haven't touched it yet.  Will remove now
