### ISSUE TITLE
Deploy Registry-Sweeper in MCP Prod

### ISSUE THREAD

**Issue by sjoshi-jpl** [NASA-PDS/registry-sweepers#135]
### 💡 Description

Deploy Registry-Sweeper ECS Task and Task Definition in MCP Prod

**Comment by alexdunnjpl** [comment]
Branch `fargate-support` has been side-loaded to ECR under the assumption that the following - which could not be corroborated - was correct:

> AWS automatically injects temporary security credentials into the environment of the container running inside the Fargate task. These credentials are accessible through standard environment variables:
> 
>     AWS_ACCESS_KEY_ID
>     AWS_SECRET_ACCESS_KEY
>     AWS_SESSION_TOKEN
> 
> If you are using an AWS SDK (e.g., boto3 for Python, AWS SDK for Java, etc.), the SDK will automatically use the credentials injected into the container.

Unfortunately, this does not appear to be correct, so it remains unclear how to manually (without boto3) get credentials for the task role from within Fargate (as opposed to EC2).

@sjoshi-jpl is EC2-based ECS a possibility here, as a stopgap or backup?

**Comment by tloubrieu-jpl** [comment]
Environment is different in ECS than EC2, this needs to be managed.

**Comment by alexdunnjpl** [comment]
Supported by #145

**Comment by nutjob4life** [comment]
Image updated to ECR, Sagar handling deployment

**Comment by jordanpadams** [comment]
Done! 🎉 

All working and tested
