### ISSUE TITLE
Registry-Sweeper ECS Enchancements (Pre Multi-Tenancy)

### ISSUE THREAD

**Issue by sjoshi-jpl** [NASA-PDS/registry-sweepers#59]
## 💡 Description

All changes will be in JPL AWS.

SA team has created a registry-sweeper prod cluster for ECS in JPL AWS and following enhancements are required :

1. Move all task definitions to point to new registry-sweeper prod cluster.
2. Update all cloudwatch alarms and metrics to pull data from new registry-sweeper cluster. Also update ECS CloudWatch dashboard.
3. Update EventBridge schedules to point to the new registry-sweeper prod cluste
4. Turn on container insights for new cluster and disabled / delete old cluster (once approved by @tloubrieu-jpl or @jordanpadams
5. Ensure the new CloudWatch Alarms / SNS notifications refer to registry-sweeper terminology rather than provenanc
6. Update documentation for ECS in Private Wiki with new task-definition and cluster names.
7. Do we need to create new alarms for monitoring registry-sweeper script failures like we had one for provenance?

**Comment by sjoshi-jpl** [comment]
For point #7 above we can leverage the same lambda based solution that we have for registry-api ([#366](https://github.com/NASA-PDS/registry-api/issues/366)). Instead of having 10 different alarms being triggered (for one task per node) we can have a single lambda monitor the logs and send an SNS notification for dev teams to investigate.

**Comment by tloubrieu-jpl** [comment]
lambda profiles have been created.
