### ISSUE TITLE
Registry-Sweeper ECS Enchancements (Post Multi-Tenancy)

### ISSUE THREAD

**Issue by sjoshi-jpl** [NASA-PDS/registry-sweepers#60]
## 💡 Description

All changes will be in MCP. This was being tracked under #31 

1. Create everything described below in MCP in order to kick off a Lambda Function to manage registry-sweeper tasks.

- Prod Registry Sweepers ECS cluster
- Create a task execution role (like am-ecs-task-execution) and another assume role for ECS (am-ecs-assume-role). The task definition roles will have all the permissions to interact with services required by the ecs task. The assume role will have permission to run the actual task-definition.
- New lambda function and a lambda role with following permissions :

lambda execution rights, sns publish, cloudwatch logs
dynamodb read access
run ecs tasks, stop ecs tasks
publish to sns topic pds-provenance-alarm
query, scan and get items from dynamodb tables starting with pds-registry-sweepers*
ecs task role that can create/read/write to dynamodb any table starting with pds-registry-sweepers-*

- Add ability for your SSO role to pass the new lambda role to lambda and create dynamodb tables

Susan created all of this under DSIO # 4341 in JPL AWS, so she can provide more details.

2. The above lambda function will be triggered using an EventBridge schedule that runs hourly.
3. We will also need to re-create all the CloudWatch Alarms / Monitoring in MCP using Terraform.

**Comment by tloubrieu-jpl** [comment]
This ticket is about preventing registry-sweeper tasks to start before the previous tasks are done.
