### ISSUE TITLE
Refresh ancestry metadata on all nodes

### ISSUE THREAD

**Issue by alexdunnjpl** [NASA-PDS/registry-sweepers#85]
## 💡 Description
See #83 

Ancestry metadata has been written to all swept domains, but without the fields added to the index.

Current versions of registry-sweepers ensure index state, but this is not retroactive.  No-op updates do not trigger re-indexing, so it's necessary to either re-index or (much simpler) run a local instance of the ancestry sweeper against each node, setting the following in ancestry's `generate_updates()`

```
update_content = {
    METADATA_PARENT_BUNDLE_KEY: ["DEVELOPMENT PLACEHOLDER"],
    METADATA_PARENT_COLLECTION_KEY: ["DEVELOPMENT PLACEHOLDER"],
}
```

This will trigger index updates for the relevant fields, and the next ECS sweeper run will set the values back to what they should be.

- [ ] atm-prod
  - [x] placeholder values started
  - [x] placeholder values complete
- [x] en-prod
  - [x] placeholder values started
  - [x] placeholder values complete
- [x] geo-prod
  - [x] placeholder values started
  - [x] placeholder values complete
- [ ] img-prod (manually applying repairkit, too)
  - [x] placeholder values started
  - [x] placeholder values complete
- [ ] naif-prod
  - [x] placeholder values started
  - [x] placeholder values complete
- [ ] ppi-prod
  - [x] placeholder values started
  - [x] placeholder values complete
- [ ] psa-prod (**IN PROGRESS - REPEATED RUNS REQUIRED UNTIL NO OUTSTANDING DOCS**)
  - [x] placeholder values started
  - [x] placeholder values complete
- [ ] rms-prod
  - [x] placeholder values started
  - [x] placeholder values complete
- [ ] sbnpsi-prod
  - [x] placeholder values started
  - [x] placeholder values complete
- [ ] sbnumb-prod
  - [x] placeholder values started
  - [x] placeholder values complete

**Comment by alexdunnjpl** [comment]
@jordanpadams please triage.  This won't take a lot of active work time - mostly a matter of collecting the creds for each node and running the sweepers in the background.

**Comment by jordanpadams** [comment]
@alexdunnjpl per the credentials, we have an admin user we can use for this.

**Comment by alexdunnjpl** [comment]
@jordanpadams it should be sufficient to write the placeholder values, as they'll be overwritten when the next ECS sweeper instance occurs.

Okay to close this once the last couple of nodes complete?

**Comment by jordanpadams** [comment]
@alexdunnjpl let me know if there is anything you need from me to help with this. PSA does have by far the largest data volume.

**Comment by alexdunnjpl** [comment]
@jordanpadams I should be able to sort this myself tomorrow, thanks though!

**Comment by alexdunnjpl** [comment]
Fix for PSA is sitting in my IDE - will hold off on pulling the trigger until @sjoshi-jpl has confirmed PSA sweeper execution/scheduling paused, so as to avoid overlapping load.

**Comment by alexdunnjpl** [comment]
psa complete

Still need #39 implementation before PSA can be redeployed/re-enabled and the placeholders overwritten
