### ISSUE TITLE
Property values returned by the API are inconsistent, as list or single value.

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-sweepers#86]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

When I did this request in production:
```
curl --get 'https://pds.nasa.gov/api/search/1/classes/collections' \
    --data-urlencode 'limit=10' \
    --data-urlencode 'q=(pds:Primary_Result_Summary.pds:processing_level eq "Raw")' \
  --data-urlencode 'fields=pds:Primary_Result_Summary.pds:processing_level' \
--header 'Accept:text/csv'

```

The response is:

```
"[Raw, Calibrated]"
"[Raw, Partially Processed, Calibrated, Derived]"
"[Raw]"
"[Raw]"
"[Raw]"
"[Raw]"
"Raw"
"Raw"
"Raw"
"Raw"
```

The brackets inside the quote should be fixed by as soon as https://github.com/NASA-PDS/registry-api/issues/381 is deployed in production.

But the fact that some values don't have brackets is unexpected since we have registry-sweeper cleaning these data.

Note that the same happens for field example "pds:Time_Coordinates/pds:start_date_time" and I guess a lot of other fields.

### 🕵️ Expected behavior

I expected [...]

### 📜 To Reproduce

1.
2.
3.
...

### 🖥 Environment Info

- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...

### 🦄 Related requirements

🦄 #xyz

**Comment by tloubrieu-jpl** [comment]
@alexdunnjpl @jordanpadams  for non ops properties we have a patch in the registry-api which transform single values in lists but that only works on application/json format. See for example:

curl --get 'https://pds.nasa.gov/api/search/1/classes/collections' \
    --data-urlencode 'limit=10' \
    --data-urlencode 'q=(pds:Primary_Result_Summary.pds:processing_level eq "Raw")' \
  --data-urlencode 'fields=pds:Primary_Result_Summary.pds:processing_level' | json_pp

I made that development 2 years ago and I also missed the non json serialization of the results in this patch, reason why it does not work in my examples.

I think I would transfer ticket to registry-api and make the fix there to be consistent with what has already been done for the application/json format.

We can discuss that at the breakout.

**Comment by alexdunnjpl** [comment]
@tloubrieu-jpl roger that - sounds like there's some requirements to untangle

**Comment by jordanpadams** [comment]
@tloubrieu-jpl sounds good. I do remember you making that fix, so this all track why we kept running into this even after the fact.
