### ISSUE TITLE
Test latest sweeper changes on all production OpenSearch clusters

### ISSUE THREAD

**Issue by sjoshi-jpl** [NASA-PDS/registry-sweepers#98]
### 💡 Description

Test latest sweeper profile memory changes : https://github.com/NASA-PDS/registry-sweepers/pull/93

**Comment by alexdunnjpl** [comment]
Temporarily holding off on deploying result of #100 #101 to ECR, so as not to confuse current tests

**Comment by alexdunnjpl** [comment]
Running local sweeper against IMG to benchmark memory usage and confirm presence of expected log line.

IMG schedule disabled until further notice, must be re-enabled

**Comment by alexdunnjpl** [comment]
IMG has been re-enabled (inferring from @sjoshi-jpl slack message yesterday)

PSA is running locally, and should be able to run in ECS after completion

Latest (circa #105 ) software deployed to ECR

**Comment by tloubrieu-jpl** [comment]
PDS still to be done.

**Comment by tloubrieu-jpl** [comment]
Waiting for PSA initial sweep to be be done from an on-prem instance.
